# Title
page_title                                : sNotz - Notes & Checklists

fdroid_link                               : https://f-droid.org/packages/com.sunilpaulmathew.snotz
playstore_link                            : https://play.google.com/store/apps/details?id=com.sunilpaulmathew.snotz
presskit_download_link                    : 
app_icon                                  : assets/appicon.png
app_name                                  : sNotz - Notes & Checklists
app_price                                 : Free
app_description                           : An open-source, privacy-friendly, and completely offline application, which will let you create, customize, and manage simple notes and checklists.

enable_smart_app_banner                   : true

# Informations
your_name                                 : sunilpaulmathew        
email_address                             : smartpack.org@gmail.com
github_username                           : sunilpaulmathew

# Features
features                                  :

  - title                                 : Simple & Elegant
    description                           : Create beautiful notes and checklists in few clicks
    fontawesome_icon_name                 : magic

  - title                                 : Colorful Widgets
    description                           : Add your notes/checklists as home screen widgets in your favourite color
    fontawesome_icon_name                 : eye-dropper

  - title                                 : Privacy-friendly
    description                           : sNotz respects your privacy (no data collection, storing, or sharing
    fontawesome_icon_name                 : user-secret

  - title                                 : Compatibility
    description                           : Supports Android 4.2 (Jelly Bean) and above, compatible with dark and light modes, etc.
    fontawesome_icon_name                 : mobile-alt

  - title                                 : Multilingual
    description                           : Thanks to the community contributions, sNotz is available in many languages
    fontawesome_icon_name                 : globe

  - title                                 : Open-Source
    description                           : Up-to-date source code, which is always open for suggestions/contributions
    fontawesome_icon_name                 : code-branch


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : blue

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"


####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
